test_that("amatrix.models exposes model-core workflows", {
  set.seed(21)
  X <- cbind(1, matrix(rnorm(40), nrow = 10, ncol = 4))
  beta <- matrix(rnorm(15), nrow = 5, ncol = 3)
  Y <- X %*% beta + matrix(rnorm(30, sd = 1e-6), nrow = 10, ncol = 3)
  Y_array <- array(Y, dim = c(10, 3, 1))
  w <- seq_len(nrow(X)) / nrow(X)
  X_am <- amatrix::adgeMatrix(X)

  many_obj <- many_lm(X_am, Y, method = "qr", cache = TRUE)
  many_obj_reuse <- many_lm(X_am, Y, method = "qr", cache = TRUE)
  lm_obj <- lm_fit(X_am, Y, method = "qr")
  ridge_obj <- ridge_fit(X_am, Y, lambda = 0.5)
  wls_obj <- wls_fit(X_am, Y, weights = w, method = "qr")
  cov_obj <- covariance(X_am)
  cor_obj <- correlation(X_am)
  many_weighted_obj <- many_lm(X_am, Y, weights = w, method = "qr")
  array_obj <- array_lm(X_am, Y_array, weights = w, method = "qr")

  expect_s3_class(many_obj, "am_many_lm_fit")
  expect_s3_class(lm_obj, "lm_fit")
  expect_s3_class(ridge_obj, "ridge_fit")
  expect_s3_class(wls_obj, "wls_fit")
  expect_s3_class(many_weighted_obj, "am_many_lm_fit")
  expect_s3_class(array_obj, "am_array_lm_fit")
  expect_s4_class(cov_obj, "adgeMatrix")
  expect_s4_class(cor_obj, "adgeMatrix")

  expect_identical(many_obj$method, "qr")
  expect_false(many_obj$cache_reused)
  expect_true(many_obj_reuse$cache_reused)
  expect_equal(as.matrix(stats::coef(wls_obj)), as.matrix(stats::coef(many_weighted_obj)), tolerance = 1e-8)
  expect_equal(as.matrix(cov_obj), stats::cov(X), tolerance = 1e-8)
  expect_equal(as.matrix(cor_obj), stats::cor(X), tolerance = 1e-8)
  expect_equal(array_obj$weights, as.double(w))
  expect_identical(array_obj$response_dims, c(3L, 1L))
})
